### ISSUE TITLE
Chain attribute crashes server when used.

### ISSUE THREAD

**Issue by ghost** [TheXFactor117/Loot-Slash-Conquer-Pre1.14#35]
A player got a weapon with the "Chained" attribute, and any time they swing the weapon, it spams the console and kills the game.

**Comment by ghost** [comment]
Mod Version: 0.6.1.2

Crash Report: ~[WeaponUtils.class:?]
    at thexfactor117.lsc.events.combat.EventLivingHurtAttack.onLivingAttack(EventLivingHurtAttack.java:129) ~[EventLivingHurtAttack.class:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_86_EventLivingHurtAttack_onLivingAttack_LivingAttackEvent.invoke(.dynamic) ~[?:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
    at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:572) ~[ForgeHooks.class:?]
    at net.minecraft.entity.EntityLivingBase.attackEntityFrom(EntityLivingBase.java:848) ~[vp.class:?]
    at net.minecraft.entity.monster.EntityMob.attackEntityFrom(EntityMob.java:70) ~[ade.class:?]
    at net.minecraft.entity.monster.EntityZombie.attackEntityFrom(EntityZombie.java:233) ~[adt.class:?]
    at thexfactor117.lsc.player.WeaponUtils.useWeaponAttributes(WeaponUtils.java:97) ~[WeaponUtils.class:?]
    at thexfactor117.lsc.events.combat.EventLivingHurtAttack.onLivingAttack(EventLivingHurtAttack.java:129)

Forge version: 1.12.2-14.23.4.2738

Other mods: (attached picture)

Known issue: Chained attribute causing server to crash.

**Comment by DuNamarSundavar** [comment]
Might try using the latest recommended version of Forge first, instead of using a developmental build. That might clear up some code errors on Minecraft's side. The issue with Chained is a mod issue that TheXFactor117 has finished working on and will be pushed out as part of the initial Alpha 7 release - refer to the closed Issue 26 for more info.
